---
- name: Ensure that the {{ adguard_package }} package is installed
  tags: adguard
  homebrew_cask:
    name: "{{ adguard_package|lower }}"
    state: present
  register: adguard_homebrew_cask

- name: Attempting to apply {{ adguard_package }} configurations
  tags: adguard
  osx_defaults:
    domain: "{{ adguard_domain }}"
    key: "{{ item.key|regex_replace('_', ' ') }}"
    state: "{{ item.value.state|default('present') }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ adguard_defaults }}"
  when:
    - item.key is defined
    - item.value.type is defined
    - item.value.value is defined
    - adguard_defaults|length > 0
    - adguard_homebrew_cask is success
...
