---
- name: Ensure that the {{ adguard_package }} package is installed
  tags: adguard
  homebrew_cask:
    name: "{{ adguard_package|lower }}"
    state: present
  when: adguard_package|length > 0

- name: Attempting to apply {{ adguard_package }} configurations
  tags: adguard
  osx_defaults:
    domain: "{{ adguard_domain }}"
    key: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ adguard_defaults }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - item.type is defined
    - item.value is defined
    - adguard_defaults|length > 0
    - adguard_domain is defined
...
